language: go
install: go get -v github.com/gohugoio/hugo
script:
  - hugo
after_success:
  - python --version
  - sudo pip install s3cmd
  - s3cmd sync --delete-removed -P -M -r public/ s3://twistedcode.org/ --no-mime-magic
notifications:
    email:
        on_failure: always